// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilityBillingSystem.Infrastructure.Data;

#nullable disable

namespace UtilityBillingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251230111629_updatedwithbillspayments")]
    partial class updatedwithbillspayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BillingCycleId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnergyCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<int>("MeterReadingId")
                        .HasColumnType("int");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillId");

                    b.HasIndex("BillNumber")
                        .IsUnique();

                    b.HasIndex("BillingCycleId");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("MeterReadingId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.BillingCycle", b =>
                {
                    b.Property<int>("BillingCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillingCycleId"));

                    b.Property<DateTime>("BillGenerationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MeterReadingDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PenaltyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BillingCycleId");

                    b.ToTable("BillingCycles");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Connection", b =>
                {
                    b.Property<int>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectionId"));

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConnectionLoad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisconnectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisconnectionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InitialReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TariffId")
                        .HasColumnType("int");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("int");

                    b.HasKey("ConnectionId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("MeterNumber")
                        .IsUnique();

                    b.HasIndex("TariffId");

                    b.HasIndex("UtilityTypeId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Consumer", b =>
                {
                    b.Property<int>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsumerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProofNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProofType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ConsumerId");

                    b.HasIndex("ConsumerCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Consumers");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.MeterReading", b =>
                {
                    b.Property<int>("MeterReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeterReadingId"));

                    b.Property<int>("BillingCycleId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsBillGenerated")
                        .HasColumnType("bit");

                    b.Property<decimal>("PreviousReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeterReadingId");

                    b.HasIndex("BillingCycleId");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("RecordedBy");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillId");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("RecordedBy");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FixedMonthlyCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FlatRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSlabBased")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("int");

                    b.HasKey("TariffId");

                    b.HasIndex("UtilityTypeId");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.TariffSlab", b =>
                {
                    b.Property<int>("TariffSlabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffSlabId"));

                    b.Property<decimal>("FromUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RatePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlabNumber")
                        .HasColumnType("int");

                    b.Property<int>("TariffId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ToUnit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TariffSlabId");

                    b.HasIndex("TariffId");

                    b.ToTable("TariffSlabs");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdProofNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProofType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Admin Office",
                            City = "Jamshedpur",
                            CreatedAt = new DateTime(2025, 12, 30, 11, 16, 28, 220, DateTimeKind.Utc).AddTicks(9508),
                            Email = "admin@utilitybilling.com",
                            FatherName = "N/A",
                            FirstName = "System",
                            IdProofNumber = "ADMIN001",
                            IdProofType = "Official",
                            IsActive = true,
                            IsApproved = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$P.vSdDkWFBOTRt934Pnj1.hw03PKuD0VA9LgTzINpKpVxYcWQw5/6",
                            Phone = "9999999999",
                            PinCode = "831001",
                            Role = 1,
                            State = "Jharkhand"
                        });
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.UtilityType", b =>
                {
                    b.Property<int>("UtilityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityTypeId"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UtilityTypeId");

                    b.ToTable("UtilityTypes");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Bill", b =>
                {
                    b.HasOne("UtilityBillingSystem.Core.Entities.BillingCycle", "BillingCycle")
                        .WithMany("Bills")
                        .HasForeignKey("BillingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.Connection", "Connection")
                        .WithMany("Bills")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.Consumer", "Consumer")
                        .WithMany("Bills")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.MeterReading", "MeterReading")
                        .WithMany()
                        .HasForeignKey("MeterReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingCycle");

                    b.Navigation("Connection");

                    b.Navigation("Consumer");

                    b.Navigation("GeneratedByUser");

                    b.Navigation("MeterReading");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Connection", b =>
                {
                    b.HasOne("UtilityBillingSystem.Core.Entities.Consumer", "Consumer")
                        .WithMany("Connections")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.Tariff", "Tariff")
                        .WithMany("Connections")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.UtilityType", "UtilityType")
                        .WithMany("Connections")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consumer");

                    b.Navigation("Tariff");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Consumer", b =>
                {
                    b.HasOne("UtilityBillingSystem.Core.Entities.User", "User")
                        .WithOne("Consumer")
                        .HasForeignKey("UtilityBillingSystem.Core.Entities.Consumer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.MeterReading", b =>
                {
                    b.HasOne("UtilityBillingSystem.Core.Entities.BillingCycle", "BillingCycle")
                        .WithMany("MeterReadings")
                        .HasForeignKey("BillingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.Connection", "Connection")
                        .WithMany("MeterReadings")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingCycle");

                    b.Navigation("Connection");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Payment", b =>
                {
                    b.HasOne("UtilityBillingSystem.Core.Entities.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.Consumer", "Consumer")
                        .WithMany("Payments")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityBillingSystem.Core.Entities.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Consumer");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Tariff", b =>
                {
                    b.HasOne("UtilityBillingSystem.Core.Entities.UtilityType", "UtilityType")
                        .WithMany("Tariffs")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.TariffSlab", b =>
                {
                    b.HasOne("UtilityBillingSystem.Core.Entities.Tariff", "Tariff")
                        .WithMany("TariffSlabs")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.User", b =>
                {
                    b.HasOne("UtilityBillingSystem.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Bill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.BillingCycle", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Connection", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Consumer", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Connections");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.Tariff", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("TariffSlabs");
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.User", b =>
                {
                    b.Navigation("Consumer")
                        .IsRequired();
                });

            modelBuilder.Entity("UtilityBillingSystem.Core.Entities.UtilityType", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Tariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
